export enum Permission {
  EXAMS_READ = 'EXAMS_READ',
  EXAMS_CREATE = 'EXAMS_CREATE',
  EXAMS_UPDATE = 'EXAMS_UPDATE',
  EXAMS_DELETE = 'EXAMS_DELETE',

  USERS_READ = 'USERS_READ',
  USERS_CREATE = 'USERS_CREATE',
  USERS_UPDATE = 'USERS_UPDATE',
  USERS_DELETE = 'USERS_DELETE',
  USERS_IMPORT_CSV = 'USERS_IMPORT_CSV',
  USERS_EXPORT_CSV = 'USERS_EXPORT_CSV',

  APPOINTMENTS_CREATE = 'APPOINTMENTS_CREATE',
  APPOINTMENTS_READ_OWN = 'APPOINTMENTS_READ_OWN',
  APPOINTMENTS_UPDATE = 'APPOINTMENTS_UPDATE',
  APPOINTMENTS_DELETE = 'APPOINTMENTS_DELETE',
  APPOINTMENTS_CANCEL_OWN = 'APPOINTMENTS_CANCEL_OWN',
  APPOINTMENTS_REQUEST_CHANGE_OWN = 'APPOINTMENTS_REQUEST_CHANGE_OWN',
  APPOINTMENTS_APPROVE_CHANGE = 'APPOINTMENTS_APPROVE_CHANGE',
  APPOINTMENTS_IMPORT_CSV = 'APPOINTMENTS_IMPORT_CSV',
  APPOINTMENTS_EXPORT_CSV = 'APPOINTMENTS_EXPORT_CSV',

  EXAMS_IMPORT_CSV = 'EXAMS_IMPORT_CSV',
  EXAMS_EXPORT_CSV = 'EXAMS_EXPORT_CSV',
}
